id: P844744D9
initial_creation_type: ocr
source_metadata:
  volumes:
    833fe80e9a3b46d3899605d831f036e4:
      base_file: v062.txt
      image_group_id: I1PD95907
      title: དེ་ཁོ་ན་ཉིད་སྣང་བ་ཞེས་བྱ་བའི་རབ་ཏུ་བྱེད་པ།
      total_pages: 1557
      volume_number: 62
